name: Fly Deploy Monorepo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy all Fly apps
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [db, backend, frontend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy ${{ matrix.app }}
        working-directory: ${{ matrix.app }}
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
