resources:
  pipeline_config:
    config:
      pre_processing_mode: from_scratch
      scope: batched
      refresh: false
      resume_open_batches: true
      tagging_agreement_batch_size: 10
      pre_processing_agreement_batch_size: 10
      xml_agreement_batch_size: 10
      taxonomy_agreement_batch_size: 10
      tx_metadata_agreement_batch_size: 10
      tx_metadata_mode: offline
      staging_days_to_fetch: 7
      staging_rate_limit_max_requests: 10
      staging_rate_limit_window_seconds: 1.025
      staging_max_workers: 8
      staging_use_keyword_filter: true
