// @ts-check
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

type SidebarDocItem = {
  type: "doc";
  id: string;
  label?: string;
  className?: string;
};

type SidebarLinkItem = {
  type: "link";
  href: string;
  label: string;
  className?: string;
};

type SidebarCategoryItem = {
  type: "category";
  label: string;
  link?: { type: "doc"; id: string } | { type: "generated-index"; title?: string; slug?: string };
  items: SidebarItem[];
  collapsible?: boolean;
  collapsed?: boolean;
  className?: string;
};

type SidebarItem = SidebarDocItem | SidebarLinkItem | SidebarCategoryItem;

const isDocItem = (item: SidebarItem): item is SidebarDocItem => item.type === "doc";
const isCategoryItem = (item: SidebarItem): item is SidebarCategoryItem =>
  item.type === "category";

const rawApiItems = require("./docs/pandects/sidebar.js") as SidebarItem[];

const apiReferenceItems = rawApiItems.filter(
  (item) => !(isDocItem(item) && item.id === "pandects/pandects-api"),
).map((item) => {
  if (!isCategoryItem(item)) {
    return item;
  }

  const categoryLinkDocId =
    item.link && item.link.type === "doc" ? item.link.id : undefined;
  const hasSingleEndpointItem =
    item.items.length === 1 && isDocItem(item.items[0]);

  if (!categoryLinkDocId || !hasSingleEndpointItem) {
    return item;
  }

  const endpointItem = item.items[0];
  const endpointId = endpointItem.id;

  return {
    ...item,
    link: { type: "doc", id: endpointId },
    items: [
      {
        type: "doc",
        id: categoryLinkDocId,
        className: "sidebar-hidden-category-doc",
      },
      {
        type: "link",
        href: `/docs/${endpointId}`,
        label: endpointItem.label ?? endpointId,
        className: endpointItem.className,
      },
    ],
  };
});

const sidebars: SidebarsConfig = {
  guidesSidebar: [
    {
      type: "category",
      label: "Guides",
      link: {
        type: "generated-index",
        title: "Guides",
      },
      items: [{ type: "autogenerated", dirName: "guides" }],
    },
  ],
  openApiSidebar: [
    {
      type: "category",
      label: "API Reference",
      link: {
        type: "doc",
        id: "pandects/search-sections",
      },
      collapsible: false,
      collapsed: false,
      items: apiReferenceItems,
    },
  ],
};

export default sidebars;
