name: Deploy Frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy Frontend
        run: flyctl deploy --remote-only --config frontend/fly.toml --dockerfile frontend/Dockerfile
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
